### ISSUE TITLE
Bugfix cumulativi pre-release

### ISSUE THREAD

**Issue by Bacca1997** [devcode-it/openstamanager#338]
Generali
- [x] Rivedere update_position in tutti gli actions perchè in alcuni casi sbaglia l'ordine

Preventivi
- [x] revisioni: controllare che non vengano mostrate in fattura tutte le revisioni

Anagrafiche
- [x] Plugin statistiche mostra tra i preventivi anche le varie revisioni non di default

Articoli:
- [x] Rimettere creazione categoria rapida in aggiunta articoli

Contratto
- [x] creando la fattura dal contratto non riporta l'idarticolo e non fa il movimento
- [x] Stampa consuntivo senza costi mostra i costi
    
Ordini cliente
- [x] Crendo la fattura dall'ordine e cancellando poi la fattura non vengo riportate nell'ordine le qta delle righe generiche
- [x] creando il ddt con gli importi issue #98 l'iva sull'articolo è sbagliata
- [x] Cancellando lo stesso ddt il ddt non mi riporta le qta delle righe generiche giuste nell'ordine 
- [x] stampa ordine con importi issue #98 l'iva risulta con un decimale in più
- [x] cancellando una riga dell'ordine da accesso negato

Ddt
- [x] Eliminando una riga: accesso negato
- [x] Se richiamo da url un qualsiasi ddt anche che non esiste mi rimostara la scheda ddt vuota
- [x] crea fattura da ddt, deve essere importabile anche la descrizione della riga
- [x] eliminando le righe generiche o righe evase parzialmente dalla fattura non vengono riportate le qta sul ddt (probabilmente è questo il problema degli stati ma controllare)
- [x] non funziona lo sconto globale
- [x] stampa ddt con importi issue #98 l'iva risulta con un decimale in più

Fatture
- [x] riapri fattura: accesso negato
- [x] da bozza a pagato loop infinito se si clicca su annulla
- [x] +ddt controllare che l'ordine delle righe venga rispettato
- [x] Aggiunta primanota sbaglia il calcolo se frazionata in più scadenze + controllare con importi issue #98 + partire dalla prima scadenza
- [x] crea_documento.php una volta tolta la spunta e reinserita non ricalcola il totale

Primanota
- [x] La cancellazione da errore (Unknown column 'idpreventivo' in 'where clause' - UPDATE in_interventi SET idstatointervento=(SELECT idstatointervento FROM in_statiintervento WHERE descrizione='Completato') WHERE idpreventivo='2')

Interventi
- [x] Stati intervento salva modifica su nuovo stato attività da errore
