### ISSUE TITLE
Miglioramenti minori

### ISSUE THREAD

**Issue by Dasc3er** [devcode-it/openstamanager#37]
Elenco di miglioramenti minori consigliati/da considerare/da completare per le release future.

**La lista può risultare utile per le persone che sono interessate a contribuire al progetto, per ottenere una maggiore comprensione del funzionamento generico del gestionale.**

- [x] Introdurre i campi di Rivalsa INPS/Ritenuta d'acconto sulle anagrafiche Fornitore (#29, #305)
- [x] Nascondere i rincari dalle stampe (#32)
- [x] Aggiungere il campo per la Posta Elettronica Certificata in Anagrafiche (#40)
- [ ] Introdurre la modifica di massa sulla tipologia di anagrafica? (#33)
- [x] Aggiungere le immagini degli articoli nelle liste (Preventivi, Fatture, ...)? (#32)

**Comment by Pek5892** [comment]
Introdurre la modifica di massa sulla tipologia di anagrafica? -> https://github.com/devcode-it/openstamanager/issues/1110
